<?xml version="1.0"?>
<package format="3">
  <name>experiment_cat</name>
  <version>0.1.0</version>
  <description>Nav2 integration assets for the DDSM115 differential-drive experiment robot.</description>
  <maintainer email="todo@example.com">experiment_cat maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>cat_bringup</exec_depend>
  <exec_depend>emcl2</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>ddsm115_controller</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_collision_monitor</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>rosbag2_transport</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sllidar_ros2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>zed_description</exec_depend>
  <exec_depend>zed_wrapper</exec_depend>

  <export><build_type>ament_cmake</build_type></export>
</package>
